version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3"

python:
  install:
    - requirements: requirements-dev.txt
    - method: setuptools
      path: .
    - requirements: docs/requirements.txt
