version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.6
  install:
    - requirements: requirements-dev.txt
    - method: pip
      path: .
    - requirements: docs/requirements.txt
