services:
  manylinux:
    build:
      context: ./manylinux
      args:
        ARCH: ${ARCH:-x86_64}
    environment:
      PLAT: ${BASEPLAT:-manylinux1}_${ARCH:-x86_64}
      WHICH_PYTHON: ${WHICH_PYTHON:-cp36-cp36m}
    volumes:
      - ..:/mnt
