on:
  pull_request:

name: Lint

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - name: shellcheck
        if: always()
        uses: reviewdog/action-shellcheck@v1.15
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          exclude: "./.git/*"
          fail_on_error: true

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true

  misspell:
    name: misspell
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - name: misspell
        if: always()
        uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"

  yamllint:
    name: yamllint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  pyflakes:
    name: pyflakes
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: pyflakes
        uses: reviewdog/action-pyflakes@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  pyright:
    name: pyright
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: jordemort/action-pyright@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          lib: true
